apiVersion: v1
kind: Service
metadata:
  name: energy-analytics-service
  labels:
    app: energy-analytics
spec:
  selector:
    app: energy-analytics
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30070
  type: NodePort
